/**
 * @file
 * Constants for Action types
 * Used in actions and reducers. Fill as needed
 *
 */

/* USER ACTION */
export const INITIALIZE_USER = 'INITIALIZE_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const RESET_USER = 'RESET_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const INITIALIZE_USERNAME = 'INITIALIZE_USERNAME'
/* USER ACTION */

/* ASSGINMENT ACTION */
export const INITIALIZE_ASSIGNMENTS = 'INITIALIZE_ASSIGNMENTS'

export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT'
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT'

export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT'
export const ADD_SUBJECT = 'ADD_SUBJECT'

export const OVERDUE_ASSIGNMENT = 'OVERDUE_ASSIGNMENT'
export const COMPLETE_ASSIGNMENT = 'COMPLETE_ASSIGNMENT'

export const SET_COMPLETED_ASSIGNMENTS = 'SET_COMPLETED_ASSIGNMENTS'
export const SET_OVERDUE_ASSIGNMENTS = 'SET_OVERDUE_ASSIGNMENTS'

export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'
/* ASSGINMENT ACTION */
