import moment from 'moment'

export const subjects1 = [];
export const subjects2 = [
  			{
  				name:"Subject #1",
  				color:"blue",
  				assignments:[
  					{
  						name:"S1A1",
  						type:"Assignment",
  						dueDate:moment().add(3,'days'),
  					},{
  						name:"S1PS2",
  						type:"Problem Set",
  						dueDate:moment().add(9,'days'),
  					},{
  						name:"S1A3",
  						type:"Assignment",
  						dueDate:moment().add(5,'days'),
  					},{
  						name:"S1PS4",
  						type:"Problem Set",
  						dueDate:moment().add(8,'days'),
  					},{
  						name:"S1A5",
  						type:"Assignment",
  						dueDate:moment().add(1,'seconds'),
  					},{
  						name:"S1R6",
  						type:"Reading",
  						dueDate:moment().add(10,'days').add(5,'hours'),
  					},{
  						name:"S1A7",
  						type:"Assignment",
  						dueDate:moment().add(13,'days').subtract(3,'hours'),
  					},{
  						name:"S1A8",
  						type:"Assignment",
  						dueDate:moment().add(4,'days').subtract(1,'hours'),
  					}
  				]
  			},{
  				name:"Subject #2",
  				color:"violet",
  				assignments:[
  					{
  						name:"S2A1",
  						type:"Assignment",
  						dueDate:moment().add(7,'days')
  					},{
  						name:"S2E2",
  						type:"Exam",
  						dueDate:moment().add(4,'days')
  					},{
  						name:"S2A3",
  						type:"Assignment",
  						dueDate:moment().add(13,'days').add(12,'hours')
  					},{
  						name:"S2A4",
  						type:"Assignment",
  						dueDate:moment().add(3,'days').add(20,'hours')
  					},{
  						name:"S2A5",
  						type:"Assignment",
  						dueDate:moment().add(1,'seconds'),
  					}
  				]
  			},{
  				name:"Subject #3",
  				color:"orange",
  				assignments:[
  					{
  						name:"S3A1",
  						type:"Assignment",
  						dueDate:moment().add(5,'days'),
  					},{
  						name:"S3PS2",
  						type:"Problem Set",
  						dueDate:moment().add(4,'days')
  					},{
  						name:"S3E3",
  						type:"Exam",
  						dueDate:moment().add(8,'days').add(12,'hours')
  					},{
  						name:"S3A4",
  						type:"Assignment",
  						dueDate:moment().add(4,'days')
  					},{
  						name:"S3A5",
  						type:"Assignment",
  						dueDate:moment().add(13,'days').add(12,'hours')
  					},{
  						name:"S3A6",
  						type:"Assignment",
  						dueDate:moment().add(1,'seconds'),
  					}

  				]
  			}, {
  				name:"Subject #4",
  				color:"purple",
  				assignments:[
  					{
  						name:"S4A1",
  						type:"Assignment",
  						dueDate:moment().add(6,'days'),
  					},{
  						name:"S4R2",
  						type:"Reading",
  						dueDate:moment().add(9,'days'),
  					},{
  						name:"S4A3",
  						type:"Assignment",
  						dueDate:moment().add(2,'days').subtract(1,'hours'),
  					},{
  						name:"S4A4",
  						type:"Assignment",
  						dueDate:moment().add(1,'days').add(4,'hours'),
  					},{
  						name:"S4A5",
  						type:"Assignment",
  						dueDate:moment().add(12,'days').add(9,'hours'),
  					},{
  						name:"S4A6",
  						type:"Assignment",
  						dueDate:moment().add(5,'days').add(4,'hours'),
  					},{
  						name:"S4A7",
  						type:"Assignment",
  						dueDate:moment().add(4,'days').add(9,'hours'),
  					},{
  						name:"S4A8",
  						type:"Assignment",
  						dueDate:moment().add(11,'days').add(4,'hours'),
  					},{
  						name:"S4E9",
  						type:"Exam",
  						dueDate:moment().add(3,'days').add(9,'hours'),
  					},{
  						name:"S4A10",
  						type:"Assignment",
  						dueDate:moment().add(1,'seconds'),
  					}
  				]
  			},{
  				name:"Subject #5",
  				color:"darkgreen",
  				assignments:[
  					{
  						name:"S5R1",
  						type:"Reading",
  						dueDate:moment().add(2,'days'),
  					},{
  						name:"S5A2",
  						type:"Assignment",
  						dueDate:moment().add(8,'days'),
  					},{
  						name:"S5A3",
  						type:"Assignment",
  						dueDate:moment().add(2,'days').subtract(1,'hours'),
  					},{
  						name:"S5A4",
  						type:"Assignment",
  						dueDate:moment().add(11,'days').add(4,'hours'),
  					},{
  						name:"S5R5",
  						type:"Reading",
  						dueDate:moment().add(5,'days').add(3,'hours'),
  					},{
  						name:"S5A6",
  						type:"Assignment",
  						dueDate:moment().add(10,'days').add(4,'hours'),
  					},{
  						name:"S5R7",
  						type:"Reading",
  						dueDate:moment().add(6,'days').add(9,'hours'),
  					},{
  						name:"S5A8",
  						type:"Assignment",
  						dueDate:moment().add(12,'days').add(4,'hours'),
  					},{
  						name:"S5E9",
  						type:"Exam",
  						dueDate:moment().add(6,'days').add(9,'hours'),
  					},{
  						name:"S5A10",
  						type:"Assignment",
  						dueDate:moment().add(7,'days').subtract(30,'minutes'),
  					},{
  						name:"S5A11",
  						type:"Assignment",
  						dueDate:moment().add(1,'seconds'),
  					}
  				]
  			}
  	];

export const colors1 = {
	typeColors:{
		assignment:'white',
		exam:'maroon',
		reading:'cyan',
		problemset:'magenta'
	}
}
